c
**************************************************
      SUBROUTINE INSIDE(X,Y,XB,YB,NB,IND)

C     GIVEN A POINT X,Y AND THE SERIES XB(K),YB(K) (K=1...NB) DEFINING
C     VERTICES OF A CLOSED POLYGON.  IND IS SET TO 1 IF THE POINT IS IN
C     THE POLYGON AND 0 IF OUTSIDE.  EACH TIME A NEW SET OF BOUND POINTS
C     IS INTRODUCED IND SHOULD BE SET TO 999 ON INPUT.
C     IT IS BEST TO DO A SERIES OF Y FOR A SINGLE FIXED X.
C     METHOD ... A COUNT IS MADE OF THE NO. OF TIMES THE BOUNDARY CUTS
C     THE MERIDIAN THRU (X,Y) SOUTH OF (X,Y).   AN ODD COUNT INDICATES
C     THE POINT IS INSIDE , EVEN INDICATES OUTSIDE.
C     SEE A LONG WAY FROM EUCLID BY CONSTANCE REID  P 174 .
C     OCEANOGRAPHY EMR   OCT/69
C
C    DIMENSION YC(MAXIMUM COUNT),XB(NB),YB(NB)
      DIMENSION XB(*),YB(*),YC(200)
      IF(NB)10,10,20
10    IND=1
      RETURN
20    IF(IND-999)30,40,30
30    IF(X-XPREV)40,300,40
C
40    XPREV=X
      NC=0
      DO 200 K=1,NB
      KP1=K+1-K*(K/NB)
      KW=K
      IF(XB(K)-XB(KP1))60,200,50
50    KW=KP1
60    KE=K+KP1-KW
      IF(X-XB(KE))80,90,200
80    IF(X-XB(KW))200,200,90
90    NC=NC+1
      SLOPE=(YB(KE)-YB(KW))/(XB(KE)-XB(KW))
      YC(NC)=YB(KW)+(X-XB(KW))*SLOPE
200   CONTINUE
C
300   IND=0
      IF(NC)340,340,310
310   DO 330 K=1,NC
      IF(YC(K)-Y)320,330,330
320   IND=1-IND
330   CONTINUE
340   RETURN
      END
******************************************************
